FROM node:argon

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY app/package.json /usr/src/app/
RUN npm install

# Bundle app and test source
COPY app /usr/src/app
COPY test /usr/src/app/test

EXPOSE 3000
CMD [ "npm", "test" ]

