
node {

   checkout scm

   docker.withRegistry('https://docker.example.com/', 'docker-registry-login') {

     stage 'build'
     def app_image = docker.build('nodejs-demo','src/demo-app')
     def app_container = app_image.run('-i --name nodejs-demo' + env.BUILD_ID)

     input "How does app look?"
     app_container.stop()

     stage 'test'
     app_image = docker.build('nodejs-demo-test','src/demo-app-tests')
     def id = runAttached(app_image, '-i --name nodejs-demo-test')

     input "How does test look?"
     //app_container.stop()
     docker.script.sh "docker stop ${id} && docker rm -f ${id}"
   }

}

def runAttached(image, args) {
   docker.node {
       try {
        docker.script.sh "rm .container"
       }
       catch (all) {} 
       docker.script.sh "docker run --cidfile=.container ${args != '' ? ' ' + args : ''} ${image.id}"
       def container = docker.script.readFile('.container').trim()
       docker.script.dockerFingerprintRun containerId: container, toolName: docker.script.env.DOCKER_TOOL_NAME
       return container
   }
}

