
node {

   checkout scm

   docker.withRegistry('https://docker.example.com/', 'docker-registry-login') {
     stage 'build'
     def app_image = docker.build('nodejs-demo','src/demo-app')
     def app_container = app_image.run("-i --name nodejs-demo-${env.BUILD_ID}")

     stage 'unit tests'
     app_image = docker.build('nodejs-demo-unit-tests','src/demo-app-unit-tests')
     def unit-id = runAttached(app_image, "-i --name nodejs-demo-unit-tests-${env.BUILD_ID}")

     stage 'integration tests'
     app_image = docker.build('nodejs-demo-int-tests','src/demo-app-int-tests')
     def int-id = runAttached(app_image, "-i --link nodejs-demo-${env.BUILD_ID}:demohost --name nodejs-demo-int-tests-${env.BUILD_ID}")

     app_container.stop()
     docker.script.sh "docker stop ${unit-id} && docker rm -f ${unit-id}"
     docker.script.sh "docker stop ${int-id} && docker rm -f ${int-id}"
   }

}

def runAttached(image, args) {
   docker.node {
       try {
        docker.script.sh "rm .container"
       }
       catch (all) {} 
       docker.script.sh "docker run --cidfile=.container ${args != '' ? ' ' + args : ''} ${image.id}"
       def container = docker.script.readFile('.container').trim()
       docker.script.dockerFingerprintRun containerId: container, toolName: docker.script.env.DOCKER_TOOL_NAME
       return container
   }
}

